### ISSUE TITLE
Release notes are duplicated under each category for which they are labelled

### ISSUE THREAD

**Issue by onyiny-ang** [marpaia/release-notes#3]
Currently release-notes with multiple labels are duplicated in the generated doc under each category they are labelled with. This creates a very bulky release-note document with the potential for unnecessary duplication.

Many of the release notes with duplicates seem to appear under the label kind/feature which is categorized as "New Features". This label is arguably more interesting to the casual user of kubernetes and so one possible solution for the duplicates here is to keep anything appearing under New Features, remove any duplicates and add a line to that note that acknowledges every other sig that the note is labelled with.
Example:
```
New Features

- The foo API is now beta  ([#???](https://github.com/kubernetes/kubernetes/pull/???), [@k8suser](https://github.com/k8suser)) Courtesy of: SIG Node, SIG API-machinery, SIG cluster-lifecycle
. . .

```
The same could probably apply for the "Action Needed" category.

For any duplicate notes that don't appear in either of these two categories, we could indicate that they are duplicates and list all the labels they have so the decision whether to keep or remove them is made by  SIG-leads on final review of the draft.
Example:
```
SIG Foo

- The foo scheduler is now deprecated  ([#???](https://github.com/kubernetes/kubernetes/pull/???), [@k8suser](https://github.com/k8suser)) <DUPLICATE> Appears in: SIG Foo, SIG API-machinery, SIG auth, SIG scheduling KEEP or REMOVE
. . .
```
If we can get SIG leads to indicate KEEP or REMOVE, it would make the final edit pretty straight forward.

**Comment by nickchase** [comment]
My only concern is that if we have notes in each tagged section and we have the sig leads remove them if they don't belong in their sig, we could easily have a situation where every instance gets removed and the note disappears altogether.

**Comment by onyiny-ang** [comment]
That is a serious concern. If we are able to communicate to SIG leads to indicate KEEP or REMOVE in the case of each duplicated note, instead of actually keeping/deleting the note, the release-notes team could be responsible for the final edit to sort it out. If every SIG lead indicated REMOVE for a note, maybe it would be a candidate for the "Not Very Notable" category? On the other hand, if every SIG lead indicated KEEP it could maybe be moved to the "New Feature" categpory, the "Other notable changes" category or just kept in each category that opted to keep it.

**Comment by nickchase** [comment]
I like it.
